import type { AdminSnapshot } from "../domain";

export const controlRoomSnapshot: AdminSnapshot = {
  source: {
    kind: "snapshot",
    label: "本地验收快照",
    generatedAt: "2026-08-12T08:30:00.000Z",
    detail: "仅用于本地测试",
  },
  sources: {
    library: { kind: "snapshot", label: "静态资源索引" },
    reviews: { kind: "snapshot", label: "审核验收数据" },
    pipelines: { kind: "snapshot", label: "管线验收数据" },
    sync: { kind: "snapshot", label: "同步验收数据" },
  },
  generatedAt: "2026-08-12T08:30:00.000Z",
  assets: [
    {
      id: "asset-editorial",
      title: "Editorial Systems",
      url: "https://example.test/editorial",
      tags: ["Editorial", "Typography"],
      status: "completed",
      quality: { evidence: "E3", curation: "recommended", origin: "alive" },
      hasSpec: true,
      hasPack: true,
      publicPath: "/zh-CN/sites/editorial-systems",
      packPath: "/packs/editorial-systems/",
      artifacts: {
        preview: { status: "ready", path: "/previews/editorial.webp" },
        spec: { status: "ready", path: "/zh-CN/sites/editorial-systems" },
        pack: { status: "ready", path: "/packs/editorial-systems/" },
        assets: { status: "ready", path: "/packs/editorial-systems/", count: 8 },
        completeness: 100,
        issues: [],
      },
    },
    {
      id: "asset-origin-down",
      title: "Unavailable Origin",
      url: "https://unavailable.example.test",
      tags: ["Archive"],
      status: "needs_review",
      quality: { evidence: "E0", curation: "unreviewed", origin: "unavailable" },
      hasSpec: false,
      hasPack: false,
      publicPath: "/zh-CN/sites/unavailable-origin",
      artifacts: {
        preview: { status: "missing" }, spec: { status: "missing" },
        pack: { status: "missing" }, assets: { status: "missing" },
        completeness: 0,
        issues: ["缺少可用预览图", "缺少结构化设计规范", "缺少可复制的设计包", "设计资产清单尚未建立"],
      },
    },
  ],
  reviews: [
    {
      id: "review-discovery",
      source: "discovery",
      status: "pending",
      priority: "medium",
      title: "Discovery candidate",
      summary: "从公开设计索引发现的新候选。",
      evidence: ["source=public-index"],
      previewOnly: true,
    },
    {
      id: "review-submission",
      source: "submission",
      status: "pending",
      priority: "high",
      title: "Submission candidate",
      summary: "用户推荐但尚未审核。",
      evidence: ["requests=3"],
      previewOnly: true,
    },
    {
      id: "review-quality",
      source: "quality",
      status: "pending",
      priority: "high",
      title: "Quality regression",
      summary: "DESIGN.md 缺少可迁移的字体类别。",
      assetId: "asset-editorial",
      quality: { evidence: "E3", curation: "recommended", origin: "alive" },
      evidence: ["typography.display=brand-font"],
      previewOnly: true,
    },
    {
      id: "review-origin",
      source: "origin",
      status: "pending",
      priority: "critical",
      title: "Origin unavailable",
      summary: "源站不可用，需要人工核对。",
      assetId: "asset-origin-down",
      quality: { evidence: "E0", curation: "unreviewed", origin: "unavailable" },
      evidence: ["origin_status=unavailable"],
      previewOnly: true,
    },
  ],
  decisions: [
    {
      id: "decision-ad",
      candidateId: "candidate-ad",
      candidateTitle: "AI tools coupon directory",
      candidateUrl: "https://ads.example.test",
      recommendation: "reject",
      confidence: 96,
      reason: "广告和联盟跳转占主导，缺少原创设计证据。",
      policyVersion: "opendesign-curation-v1.0",
      model: "mimo-v2.5",
      decidedAt: "2026-08-12T08:20:00.000Z",
      reviewStatus: "pending",
      signals: [
        { id: "design-value", label: "设计价值", state: "warn", score: 40, evidence: ["页面模板化"] },
        { id: "originality", label: "原创性", state: "fail", score: 18, evidence: ["内容重复"] },
        { id: "utility", label: "可复用性", state: "fail", score: 20, evidence: ["无 token 价值"] },
        { id: "evidence", label: "证据完整度", state: "warn", score: 35, evidence: ["仅元信息"] },
        { id: "spam-risk", label: "垃圾风险", state: "fail", score: 93, evidence: ["关键词堆叠"] },
        { id: "ad-risk", label: "广告风险", state: "fail", score: 97, evidence: ["联盟链接"] },
        { id: "safety", label: "安全", state: "pass", score: 90, evidence: ["未发现恶意下载"] },
      ],
      source: { kind: "snapshot", label: "每日 AI 决策快照" },
      previewOnly: true,
    },
  ],
  pipelines: [
    {
      id: "pipeline-failed",
      kind: "collect",
      label: "Collect unavailable-origin",
      status: "failed",
      summary: "质量门失败，未进入后续阶段。",
      checkpoints: [
        { id: "discover", label: "Discover", status: "completed" },
        { id: "quality", label: "Quality gate", status: "failed", detail: "缺少设计规范" },
        { id: "build", label: "Build", status: "pending" },
      ],
      retryFromCheckpointId: "quality",
      previewOnly: true,
    },
    {
      id: "pipeline-success",
      kind: "validate",
      label: "Validate editorial-systems",
      status: "completed",
      checkpoints: [
        { id: "schema", label: "Schema", status: "completed" },
        { id: "content", label: "Content quality", status: "completed" },
      ],
      previewOnly: true,
    },
  ],
  sync: {
    state: "attention",
    summary: "GitHub 与 Public 存在只读漂移信号。",
    branch: "feature/library-admin-v2",
    localRevision: "local-123",
    nodes: [
      { location: "database", label: "Database", state: "unknown", drift: "unknown", detail: "Phase 1 未连接生产数据库" },
      { location: "local", label: "Local", state: "attention", drift: "ahead", revision: "local-123" },
      { location: "git", label: "Git", state: "healthy", drift: "in-sync", revision: "local-123" },
      { location: "github", label: "GitHub", state: "attention", drift: "behind", revision: "github-122" },
      { location: "public", label: "Public", state: "unknown", drift: "unknown" },
    ],
    readOnly: true,
  },
  today: {
    state: "blocked",
    topActions: [
      {
        id: "action-origin",
        kind: "review",
        priority: "critical",
        title: "处理不可用源站",
        summary: "先确认公开资源是否需要降级。",
        target: "review",
        targetId: "review-origin",
        previewOnly: true,
      },
      {
        id: "action-pipeline",
        kind: "pipeline",
        priority: "high",
        title: "定位失败检查点",
        summary: "质量门失败，检查输入证据。",
        target: "pipelines",
        targetId: "pipeline-failed",
        previewOnly: true,
      },
      {
        id: "action-sync",
        kind: "sync",
        priority: "high",
        title: "核对 GitHub 漂移",
        summary: "只读检查本地、GitHub 与公开页差异。",
        target: "sync",
        previewOnly: true,
      },
    ],
    funnel: {
      totalAssets: 2,
      withSpec: 1,
      withPack: 1,
      accepted: 0,
      recommended: 1,
      pendingReviews: 4,
    },
    pipelineSignal: "blocked",
    syncSignal: "attention",
    decisionSignal: "blocked",
  },
  diagnostics: [
    { code: "snapshot-only", level: "warning", message: "当前数据来自本地只读快照。" },
  ],
};

export const emptyControlRoomSnapshot: AdminSnapshot = {
  ...controlRoomSnapshot,
  assets: [],
  reviews: [],
  decisions: [],
  pipelines: [],
  today: {
    state: "healthy",
    topActions: [],
    funnel: {
      totalAssets: 0,
      withSpec: 0,
      withPack: 0,
      accepted: 0,
      recommended: 0,
      pendingReviews: 0,
    },
    pipelineSignal: "unknown",
    syncSignal: "unknown",
    decisionSignal: "unknown",
  },
};
